# Generated by Django 5.1.1 on 2025-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_routestbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='managebustbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=100)),
                ('routeid', models.CharField(max_length=100)),
                ('dtime', models.CharField(max_length=100)),
                ('totalseat', models.CharField(max_length=100)),
            ],
        ),
    ]
