# Generated by Django 5.1.1 on 2025-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_managebustbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='managequotastbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('cutofftime', models.CharField(max_length=100)),
            ],
        ),
    ]
