# Generated by Django 5.1.1 on 2025-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_managequotastbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='booknowtbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=100)),
                ('dtime', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('jdate', models.CharField(max_length=100)),
            ],
        ),
    ]
