# Generated by Django 5.1.1 on 2025-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booknowtbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknowtbl',
            name='quota',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
