# Generated by Django 5.1.1 on 2025-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booknowtbl_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknowtbl',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
